# START_POINT_X_Y = [0,0]
MAIN_MENU_BTN_SIZE = (150, 150)
MAIN_WINDOW_SIZE = (MAIN_MENU_BTN_SIZE[0], 7 * MAIN_MENU_BTN_SIZE[1])

ICO_DOC_BTN = './static/doc.png'
ICO_PROJ_BTN = './static/proj.png'
ICO_ATTEND_BTN = './static/attendance.png'
ICO_PROC_BTN = './static/procurement.png'
ICO_CATEGORIES_BTN = './static/categories.png'
ICO_CUSTOM_BTN = './static/custom.png'

FONT_NAME = 'Hey Comic'
FONT_PATH = './static/HeyComic.ttf'
FONT_SIZE = 16

PROCENT_OF_WINDOW = 0.8 # размер окна таблицы в % от всего экрана монитора

# input line
ID_INPUT_SIZE = (150, 50)
ID_INPUT_POSITION = (0, 0)
ID_MAX_SYMBOLS = 5

DATE_INPUT_SIZE = (150, 50)
DATE_INPUT_POSITION = (150, 0)
DATE_MAX_SYMBOLS = 10

NAME_INPUT_SIZE = (150, 50)
NAME_INPUT_POSITION = (300, 0)
NAME_MAX_SYMBOLS = 255

PRICE_ZL_INPUT_SIZE = (150, 50)
PRICE_ZL_INPUT_POSITION = (300, 0)
PRICE_ZL_MAX_SYMBOLS = 5

PRICE_EUR_INPUT_SIZE = (150, 50)
PRICE_EUR_INPUT_POSITION = (450, 0)
PRICE_EUR_MAX_SYMBOLS = 5

LINK_INPUT_SIZE = (150, 50)
LINK_INPUT_POSITION = (600, 0)
LINK_MAX_SYMBOLS = 255

DEPARTMENT_BTN_SIZE = (150, 50)
DEPARTMENT_INPUT_POSITION = (750, 0)

PROJECT_BTN_SIZE = (150, 50)
PROJECT_INPUT_POSITION = (900, 0)

COMMENT_INPUT_SIZE = (1050, 50)
COMMENT_INPUT_POSITION = (0, 50)
COMMENT_MAX_SYMBOLS = 255